#spring.application.name=TMS
#spring.datasource.url=jdbc:postgresql://localhost:1807/learn
#spring.datasource.username=postgres
#spring.datasource.password=rajat1102
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.main.allow-bean-definition-overriding=true
#docker run -e DB_HOST=host.docker.internal -e DB_PORT=1807 -e DB_USERNAME=postgres -e DB_PASSWORD=rajat1102 -p 8081:8080 dockerdocker
#>docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=admin -e POSTGRES_DB=mydb -v E:\PgesC:/var/lib/postgresql/data  --name=postgres postgres

spring.application.name=TMS
#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/learn
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://172.17.0.2:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


